### ISSUE TITLE
I am getting Exception in thread "EReader" java.lang.NoClassDefFoundError: com/sun/tools/javac/Main

### ISSUE THREAD

**Issue by ptwaragoda** [trade-manager/trade-manager#20]
Hi Simon.
First of all, you made a greate app and please keep up the good work.

I dowloaded and setup the application as per your instructions. I have IB so trading manager is getting data from my IB TWS application.

However when I try to run a strategy the progress bar goes upto 66% and stops. on the consol, i get the following error

TWS Time at connection:20151210 09:19:18 EST
Exception in thread "EReader" java.lang.NoClassDefFoundError: com/sun/tools/javac/Main
        at org.trade.core.util.Javac.compile(Javac.java:84)
        at org.trade.core.util.Javac.compile(Javac.java:101)
        at org.trade.core.util.DynamicCode$LoadedClass.compileAndLoadClass(DynamicCode.java:376)
        at org.trade.core.util.DynamicCode$LoadedClass.<init>(DynamicCode.java:355)
        at org.trade.core.util.DynamicCode.loadClass(DynamicCode.java:160)
        at org.trade.core.util.DynamicCode$MyInvocationHandler.<init>(DynamicCode.java:421)
        at org.trade.core.util.DynamicCode.newProxyInstance(DynamicCode.java:277)
        at org.trade.ui.TradeMainControllerPanel.createStrategy(TradeMainControllerPanel.java:2081)
        at org.trade.ui.TradeMainControllerPanel.historicalDataComplete(TradeMainControllerPanel.java:1092)
        at org.trade.broker.AbstractBrokerModel.fireHistoricalDataComplete(AbstractBrokerModel.java:196)
        at org.trade.broker.TWSBrokerModel.historicalData(TWSBrokerModel.java:2513)
        at com.ib.client.EReader.processMsg(EReader.java:1024)
        at com.ib.client.EReader.run(EReader.java:76)
Caused by: java.lang.ClassNotFoundException: com.sun.tools.javac.Main
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 13 more

I am using JDK1.8.0_65 on windows 10 
Could you please advise ?

**Comment by trade-manager** [comment]
Couple of questions.

Were you downloading historical data for a single day for a stock?

What time of day did you do this?

Did you create a new strategy or is just against one of the default
examples?

Can you send me a database dump so I can recreate what you were doing?
I can give u instructions re getting a DB dump (use MySQL Workbench to
export the DB)

Thanks
Simon

On Thu, Dec 10, 2015 at 8:32 AM, ptwaragoda <notifications@github.com>
wrote:

> Hi Simon.
> First of all, you made a greate app and please keep up the good work.
>
> I dowloaded and setup the application as per your instructions. I have IB
> so trading manager is getting data from my IB TWS application.
>
> However when I try to run a strategy the progress bar goes upto 66% and
> stops. on the consol, i get the following error
>
> TWS Time at connection:20151210 09:19:18 EST
> Exception in thread "EReader" java.lang.NoClassDefFoundError:
> com/sun/tools/javac/Main
> at org.trade.core.util.Javac.compile(Javac.java:84)
> at org.trade.core.util.Javac.compile(Javac.java:101)
> at
> org.trade.core.util.DynamicCode$LoadedClass.compileAndLoadClass(DynamicCode.java:376)
> at org.trade.core.util.DynamicCode$LoadedClass.(DynamicCode.java:355)
> at org.trade.core.util.DynamicCode.loadClass(DynamicCode.java:160)
> at
> org.trade.core.util.DynamicCode$MyInvocationHandler.(DynamicCode.java:421)
> at org.trade.core.util.DynamicCode.newProxyInstance(DynamicCode.java:277)
> at
> org.trade.ui.TradeMainControllerPanel.createStrategy(TradeMainControllerPanel.java:2081)
> at
> org.trade.ui.TradeMainControllerPanel.historicalDataComplete(TradeMainControllerPanel.java:1092)
> at
> org.trade.broker.AbstractBrokerModel.fireHistoricalDataComplete(AbstractBrokerModel.java:196)
> at org.trade.broker.TWSBrokerModel.historicalData(TWSBrokerModel.java:2513)
> at com.ib.client.EReader.processMsg(EReader.java:1024)
> at com.ib.client.EReader.run(EReader.java:76)
> Caused by: java.lang.ClassNotFoundException: com.sun.tools.javac.Main
> at java.net.URLClassLoader.findClass(Unknown Source)
> at java.lang.ClassLoader.loadClass(Unknown Source)
> at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
> at java.lang.ClassLoader.loadClass(Unknown Source)
> ... 13 more
>
> I am using JDK1.8.0_65 on windows 10
> Could you please advise ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/trade-manager/trade-manager/issues/20>.
>



-- 
TTFN
Simon

**Comment by trade-manager** [comment]
No response this error it probably because the toos.jar is not in the classpath
